apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actinia.fullname" . }}
  labels:
{{ include "actinia.labels" . | indent 4 }}
data:
  .pgpass: cG9zdGdpczo1NDMyOm15ZGI6YWN0aW5pYTphY3RpbmlhCg==
  .grass7: cGd8bXlkYnxhY3RpbmlhfHxwb3N0Z2lzfDU0MzIK
