apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actinia.fullname" . }}
  labels:
{{ include "actinia.labels" . | indent 4 }}
data:
  .grass7: VEJE
  .pgpass: VEJE
  .sentinel1_asf: VEJE
  .sentinel2: VEJE
  GCS_credentials: VEJE
  UP42_PROJECT_API_KEY: VEJE
  UP42_PROJECT_ID: VEJE
  WV_credentials: VEJE
