apiVersion: v1
kind: Service
metadata:
  name: {{ include "actinia.fullname" . }}
  labels:
    {{- include "actinia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: actinia-tcp
      protocol: TCP
      name: actinia-tcp
  selector:
    {{- include "actinia.selectorLabels" . | nindent 4 }}
