apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "actinia.fullname" . }}
  labels:
    {{- include "actinia.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "actinia.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "actinia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "actinia.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "actinia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-data
          image: alpine:3.13
          command: ["/bin/sh","/mnt/init-data.sh"]
          volumeMounts:
            - name: temp
              mountPath: /mnt/download
            - name: init-configmap
              mountPath: /mnt/
            - name: grassdb
              mountPath: /actinia_core/grassdb/
              {{- if .Values.persistence.grassdb.subPath }}
              subPath: {{ .Values.persistence.grassdb.subPath }}
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh']
          args: ['/src/start/start.sh']
          ports:
            - name: actinia-tcp
              containerPort: 8088
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health_check
              port: actinia-tcp
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health_check
              port: actinia-tcp
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: startup
              mountPath: /src/start
            - name: config
              mountPath: /etc/default/actinia-config
            - name: secret
              mountPath: /mnt/pgpass/
            - name: grassdb
              mountPath: /actinia_core/grassdb/
              {{- if .Values.persistence.grassdb.subPath }}
              subPath: {{ .Values.persistence.grassdb.subPath }}
              {{- end }}
            - name: userdata
              mountPath: /actinia_core/userdata/
              {{- if .Values.persistence.userdata.subPath }}
              subPath: {{ .Values.persistence.userdata.subPath }}
              {{- end }}
            - name: resources
              mountPath: /actinia_core/resources/
              {{- if .Values.persistence.resources.subPath }}
              subPath: {{ .Values.persistence.resources.subPath }}
              {{- end }}
            - name: geodata
              mountPath: /mnt/geodata/
              {{- if .Values.persistence.geodata.subPath }}
              subPath: {{ .Values.persistence.geodata.subPath }}
              {{- end }}
            - name: actinia-worker-workspace
              mountPath: /actinia_core/workspace/
              #subPath: /
          env:
            - name: DEFAULT_CONFIG_PATH
              value: /etc/default/actinia-config/actinia.cfg
      volumes:
        - name: temp
          emptyDir: {}
        - name: init-configmap
          configMap:
            name: {{ include "actinia.fullname" . }}
            items:
              - key: init-data.sh
                path: init-data.sh
        {{- if .Values.persistence.enabled }}
        - name: grassdb
          persistentVolumeClaim:
            {{- if .Values.persistence.grassdb.useExistingClaim }}
            claimName: {{ .Values.persistence.grassdb.claimName }}
            {{- else }}
            claimName: {{ include "actinia.fullname" . }}-grassdb
            {{- end }}
        - name: userdata
          persistentVolumeClaim:
            {{- if .Values.persistence.userdata.useExistingClaim }}
            claimName: {{ .Values.persistence.userdata.claimName }}
            {{- else }}
            claimName: {{ include "actinia.fullname" . }}-userdata
            {{- end }}
        - name: resources
          persistentVolumeClaim:
            {{- if .Values.persistence.resources.useExistingClaim }}
            claimName: {{ .Values.persistence.resources.claimName }}
            {{- else }}
            claimName: {{ include "actinia.fullname" . }}-resources
            {{- end }}
        - name: geodata
          persistentVolumeClaim:
            {{- if .Values.persistence.geodata.useExistingClaim }}
            claimName: {{ .Values.persistence.geodata.claimName }}
            {{- else }}
            claimName: {{ include "actinia.fullname" . }}-geodata
            {{- end }}
        {{- else }}
        - name: grassdb
          emptyDir: {}
        - name: userdata
          emptyDir: {}
        - name: resources
          emptyDir: {}
        - name: geodata
          emptyDir: {}
        - name: actinia-worker-workspace
          emptyDir: {}
        {{- end }}
        - name: startup
          configMap:
            name: {{ include "actinia.fullname" . }}
            items:
              - key: start.sh
                path: start.sh
        - name: config
          configMap:
            name: {{ include "actinia.fullname" . }}
            items:
              - key: actinia-core-config
                path: actinia.cfg
        - name: secret
          secret:
            secretName: {{ include "actinia.fullname" . }}
            items:
              - key: .pgpass
                path: .pgpass
              - key: .grass7
                path: .grass7
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: actinia-worker-workspace
      spec:
        accessModes:
          - {{ .Values.persistence.actiniaWorkerWorkspace.accessMode }}
        {{- if not ( eq .Values.persistence.actiniaWorkerWorkspace.storageClassName "default" ) }}
        storageClassName: {{ .Values.persistence.actiniaWorkerWorkspace.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.actiniaWorkerWorkspace.storageSize }}
    {{- end }}
