apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actinia.fullname" . }}-pc-templates
  labels:
{{ include "actinia.labels" . | indent 4 }}
data:
{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "resources/*.json" }}
  {{ base $path }}: |
{{ $root.Files.Get $path | indent 4}}
{{- end }}
