apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openeo-grassgis-driver.fullname" . }}-proxy
  labels:
    {{- include "openeo-grassgis-driver.labels" . | nindent 4 }}
data:
  cache.conf: |
    #/etc/nginx/conf.d/cache.conf
    proxy_cache_path /data/nginx/cache levels=1:2 keys_zone=STATIC:10m
    inactive=365d max_size=2g;

  default.conf: |
    #/etc/nginx/conf.d/default.conf
    server {
      server_tokens off;
      listen       80;
      listen  [::]:80;
      server_name  localhost;
      location /api/ {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, PUT, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Allow-Origin' '*';
      }
      location /api/v1.0/ {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, PUT, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Allow-Origin' '*';
      }
      location /api/collections {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/collections;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache            STATIC;
        proxy_cache_valid      200  100d;
        proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
      }
      location /api/v1.0/collections {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/collections;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, PUT, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_cache            STATIC;
        proxy_cache_valid      200  100d;
        proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
      }
      location /collections {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/collections;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache            STATIC;
        proxy_cache_valid      200  100d;
        proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
      }
      location / {
        proxy_pass http://{{ include "openeo-grassgis-driver.fullname" . }}/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, PUT, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Allow-Origin' '*';
      }
    }
