apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openeo-grassgis-driver.fullname" . }}
  labels:
    {{- include "openeo-grassgis-driver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openeo-grassgis-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openeo-grassgis-driver.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "openeo-grassgis-driver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 120
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["gunicorn", "-b", "0.0.0.0:5000", "-t", "60", "openeo_grass_gis_driver.main:flask_app"]
          # args: ['/src/start/start.sh']
          volumeMounts:
            - name: config
              mountPath: /etc/default/openeo-grassgis-driver
          env:
            - name: DEFAULT_CONFIG_PATH
              value: /etc/default/openeo-grassgis-driver
      volumes:
        - name: config
          configMap:
            name: {{ include "openeo-grassgis-driver.fullname" . }}
            items:
              - key: config
                path: config.ini

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
